//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Shared.UIConfigResources", typeof(UIConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Local Parameter Cache.
        /// </summary>
        public static string SystemCleanLocalParameter {
            get {
                return ResourceManager.GetString("SystemCleanLocalParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxed Layout.
        /// </summary>
        public static string UILayoutBoxed {
            get {
                return ResourceManager.GetString("UILayoutBoxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the boxed layout.
        /// </summary>
        public static string UILayoutBoxedInfo {
            get {
                return ResourceManager.GetString("UILayoutBoxedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed layout.
        /// </summary>
        public static string UILayoutFixed {
            get {
                return ResourceManager.GetString("UILayoutFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the fixed layout. You can&apos;t use fixed and boxed layouts together.
        /// </summary>
        public static string UILayoutFixedInfo {
            get {
                return ResourceManager.GetString("UILayoutFixedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Expand on Hover.
        /// </summary>
        public static string UILayoutSidebarExpand {
            get {
                return ResourceManager.GetString("UILayoutSidebarExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let the sidebar mini expand on hover.
        /// </summary>
        public static string UILayoutSidebarExpandInfo {
            get {
                return ResourceManager.GetString("UILayoutSidebarExpandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Layout.
        /// </summary>
        public static string UILayoutTitle {
            get {
                return ResourceManager.GetString("UILayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Right Sidebar Slide.
        /// </summary>
        public static string UILayoutToggleRightSidebar {
            get {
                return ResourceManager.GetString("UILayoutToggleRightSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between slide over content and push content effects.
        /// </summary>
        public static string UILayoutToggleRightSidebarInfo {
            get {
                return ResourceManager.GetString("UILayoutToggleRightSidebarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Right Sidebar Skin.
        /// </summary>
        public static string UILayoutToggleRightSidebarSkin {
            get {
                return ResourceManager.GetString("UILayoutToggleRightSidebarSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between dark and light skins for the right sidebar.
        /// </summary>
        public static string UILayoutToggleRightSidebarSkinInfo {
            get {
                return ResourceManager.GetString("UILayoutToggleRightSidebarSkinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Sidebar.
        /// </summary>
        public static string UILayoutToggleSidebar {
            get {
                return ResourceManager.GetString("UILayoutToggleSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the left sidebar&apos;s state (open or collapse).
        /// </summary>
        public static string UILayoutToggleSidebarInfo {
            get {
                return ResourceManager.GetString("UILayoutToggleSidebarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string UISkinBlack {
            get {
                return ResourceManager.GetString("UISkinBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Light.
        /// </summary>
        public static string UISkinBlackLight {
            get {
                return ResourceManager.GetString("UISkinBlackLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string UISkinBlue {
            get {
                return ResourceManager.GetString("UISkinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Light.
        /// </summary>
        public static string UISkinBlueLight {
            get {
                return ResourceManager.GetString("UISkinBlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string UISkinGreen {
            get {
                return ResourceManager.GetString("UISkinGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Light.
        /// </summary>
        public static string UISkinGreenLight {
            get {
                return ResourceManager.GetString("UISkinGreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string UISkinPurple {
            get {
                return ResourceManager.GetString("UISkinPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Light.
        /// </summary>
        public static string UISkinPurpleLight {
            get {
                return ResourceManager.GetString("UISkinPurpleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string UISkinRed {
            get {
                return ResourceManager.GetString("UISkinRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Light.
        /// </summary>
        public static string UISkinRedLight {
            get {
                return ResourceManager.GetString("UISkinRedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Skin.
        /// </summary>
        public static string UISkinTitle {
            get {
                return ResourceManager.GetString("UISkinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string UISkinYellow {
            get {
                return ResourceManager.GetString("UISkinYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Light.
        /// </summary>
        public static string UISkinYellowLight {
            get {
                return ResourceManager.GetString("UISkinYellowLight", resourceCulture);
            }
        }
    }
}
