//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Marketing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayerSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Marketing.PlayerSearch", typeof(PlayerSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active:.
        /// </summary>
        public static string AcctActive {
            get {
                return ResourceManager.GetString("AcctActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance:.
        /// </summary>
        public static string AcctBalance {
            get {
                return ResourceManager.GetString("AcctBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle:.
        /// </summary>
        public static string AcctHandle {
            get {
                return ResourceManager.GetString("AcctHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot:.
        /// </summary>
        public static string AcctSlot {
            get {
                return ResourceManager.GetString("AcctSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss:.
        /// </summary>
        public static string AcctWinLoss {
            get {
                return ResourceManager.GetString("AcctWinLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy In:.
        /// </summary>
        public static string ActivityBuyIn {
            get {
                return ResourceManager.GetString("ActivityBuyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promos Consumption:.
        /// </summary>
        public static string ActivityConsumption {
            get {
                return ResourceManager.GetString("ActivityConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop:.
        /// </summary>
        public static string ActivityDrop {
            get {
                return ResourceManager.GetString("ActivityDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Win:.
        /// </summary>
        public static string ActivityNetWin {
            get {
                return ResourceManager.GetString("ActivityNetWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Granted:.
        /// </summary>
        public static string ActivityPromotion {
            get {
                return ResourceManager.GetString("ActivityPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Time:.
        /// </summary>
        public static string ActivitySessionTime {
            get {
                return ResourceManager.GetString("ActivitySessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits:.
        /// </summary>
        public static string ActivityVisits {
            get {
                return ResourceManager.GetString("ActivityVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string CardIssueDate {
            get {
                return ResourceManager.GetString("CardIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Method.
        /// </summary>
        public static string CardIssueMethod {
            get {
                return ResourceManager.GetString("CardIssueMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card #.
        /// </summary>
        public static string CardNo {
            get {
                return ResourceManager.GetString("CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CardStatus {
            get {
                return ResourceManager.GetString("CardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        public static string CashDeskAmountIn {
            get {
                return ResourceManager.GetString("CashDeskAmountIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Out.
        /// </summary>
        public static string CashDeskAmountOut {
            get {
                return ResourceManager.GetString("CashDeskAmountOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string CashDeskCardNumber {
            get {
                return ResourceManager.GetString("CashDeskCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier Name.
        /// </summary>
        public static string CashDeskCashier {
            get {
                return ResourceManager.GetString("CashDeskCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket No..
        /// </summary>
        public static string CashDeskTicketNumber {
            get {
                return ResourceManager.GetString("CashDeskTicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string CashDeskTime {
            get {
                return ResourceManager.GetString("CashDeskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Created on:.
        /// </summary>
        public static string ContactAcctCreated {
            get {
                return ResourceManager.GetString("ContactAcctCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent:.
        /// </summary>
        public static string ContactAgent {
            get {
                return ResourceManager.GetString("ContactAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celluar #:.
        /// </summary>
        public static string ContactCelluar {
            get {
                return ResourceManager.GetString("ContactCelluar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string ContactCity {
            get {
                return ResourceManager.GetString("ContactCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string ContactCountry {
            get {
                return ResourceManager.GetString("ContactCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP:.
        /// </summary>
        public static string ContactCURP {
            get {
                return ResourceManager.GetString("ContactCURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Type:.
        /// </summary>
        public static string ContactDocType {
            get {
                return ResourceManager.GetString("ContactDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string ContactLanguage {
            get {
                return ResourceManager.GetString("ContactLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Status:.
        /// </summary>
        public static string ContactMartial {
            get {
                return ResourceManager.GetString("ContactMartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name:.
        /// </summary>
        public static string ContactNickName {
            get {
                return ResourceManager.GetString("ContactNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation:.
        /// </summary>
        public static string ContactOccupation {
            get {
                return ResourceManager.GetString("ContactOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone #:.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        public static string ContactPostalCode {
            get {
                return ResourceManager.GetString("ContactPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC:.
        /// </summary>
        public static string ContactRFC {
            get {
                return ResourceManager.GetString("ContactRFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document #:.
        /// </summary>
        public static string ContctDocumentNo {
            get {
                return ResourceManager.GetString("ContctDocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Bet.
        /// </summary>
        public static string GameHistoryAvgBet {
            get {
                return ResourceManager.GetString("GameHistoryAvgBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string GameHistoryDrop {
            get {
                return ResourceManager.GetString("GameHistoryDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (Sec).
        /// </summary>
        public static string GameHistoryDuration {
            get {
                return ResourceManager.GetString("GameHistoryDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string GameHistoryGame {
            get {
                return ResourceManager.GetString("GameHistoryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string GameHistoryProvider {
            get {
                return ResourceManager.GetString("GameHistoryProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot #.
        /// </summary>
        public static string GameHistorySlot {
            get {
                return ResourceManager.GetString("GameHistorySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string GameHistoryStart {
            get {
                return ResourceManager.GetString("GameHistoryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss.
        /// </summary>
        public static string GameHistoryWinLoss {
            get {
                return ResourceManager.GetString("GameHistoryWinLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string MKCategory {
            get {
                return ResourceManager.GetString("MKCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits non Redeemable:.
        /// </summary>
        public static string MKCredit {
            get {
                return ResourceManager.GetString("MKCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyality Points Available:.
        /// </summary>
        public static string MKLoyaltyAvailable {
            get {
                return ResourceManager.GetString("MKLoyaltyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyality Points Consumed:.
        /// </summary>
        public static string MKLoyaltyConsumed {
            get {
                return ResourceManager.GetString("MKLoyaltyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (Classic):.
        /// </summary>
        public static string MKSegmentClassic {
            get {
                return ResourceManager.GetString("MKSegmentClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (RFM):.
        /// </summary>
        public static string MKSegmentRFM {
            get {
                return ResourceManager.GetString("MKSegmentRFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string ParamCardNumber {
            get {
                return ResourceManager.GetString("ParamCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter One of Slot Machine Number, Player Name, or Player Card Number!.
        /// </summary>
        public static string ParamInvalid {
            get {
                return ResourceManager.GetString("ParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Valid Card Number!.
        /// </summary>
        public static string ParamInvalidCardNumber {
            get {
                return ResourceManager.GetString("ParamInvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Valid Slot Machine Number!.
        /// </summary>
        public static string ParamInvalidSlotMachine {
            get {
                return ResourceManager.GetString("ParamInvalidSlotMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Name.
        /// </summary>
        public static string ParamPlayerName {
            get {
                return ResourceManager.GetString("ParamPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Machine.
        /// </summary>
        public static string ParamSlotMachine {
            get {
                return ResourceManager.GetString("ParamSlotMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Bet.
        /// </summary>
        public static string PreferenceAvgBet {
            get {
                return ResourceManager.GetString("PreferenceAvgBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string PreferenceDrop {
            get {
                return ResourceManager.GetString("PreferenceDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (sec).
        /// </summary>
        public static string PreferenceDuration {
            get {
                return ResourceManager.GetString("PreferenceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string PreferenceGame {
            get {
                return ResourceManager.GetString("PreferenceGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Types.
        /// </summary>
        public static string PreferenceGameTypes {
            get {
                return ResourceManager.GetString("PreferenceGameTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string PreferenceProvider {
            get {
                return ResourceManager.GetString("PreferenceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string PreferenceVisits {
            get {
                return ResourceManager.GetString("PreferenceVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss.
        /// </summary>
        public static string PreferenceWinLoss {
            get {
                return ResourceManager.GetString("PreferenceWinLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string ProfileDOB {
            get {
                return ResourceManager.GetString("ProfileDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string ProfileFirstName {
            get {
                return ResourceManager.GetString("ProfileFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string ProfileGender {
            get {
                return ResourceManager.GetString("ProfileGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string ProfileLastName {
            get {
                return ResourceManager.GetString("ProfileLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s #:.
        /// </summary>
        public static string ProfilePlayerNo {
            get {
                return ResourceManager.GetString("ProfilePlayerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string ProfilePlayerTitle {
            get {
                return ResourceManager.GetString("ProfilePlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string PromotionAmount {
            get {
                return ResourceManager.GetString("PromotionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Time.
        /// </summary>
        public static string PromotionAssignedTime {
            get {
                return ResourceManager.GetString("PromotionAssignedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Card No..
        /// </summary>
        public static string PromotionCardNumber {
            get {
                return ResourceManager.GetString("PromotionCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string PromotionName {
            get {
                return ResourceManager.GetString("PromotionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string SubTitleAccountInfo {
            get {
                return ResourceManager.GetString("SubTitleAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity during the day.
        /// </summary>
        public static string SubTitleActivityDay {
            get {
                return ResourceManager.GetString("SubTitleActivityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity during the last month.
        /// </summary>
        public static string SubTitleActivityMonth {
            get {
                return ResourceManager.GetString("SubTitleActivityMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity during the last quarter.
        /// </summary>
        public static string SubTitleActivityQuarter {
            get {
                return ResourceManager.GetString("SubTitleActivityQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalInfo.
        /// </summary>
        public static string SubTitleAdditionalInfo {
            get {
                return ResourceManager.GetString("SubTitleAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashdesk History.
        /// </summary>
        public static string SubTitleCashdeskHistory {
            get {
                return ResourceManager.GetString("SubTitleCashdeskHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashless Cards.
        /// </summary>
        public static string SubTitleCashlessCards {
            get {
                return ResourceManager.GetString("SubTitleCashlessCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info &amp; Others.
        /// </summary>
        public static string SubTitleContactInfo {
            get {
                return ResourceManager.GetString("SubTitleContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game History.
        /// </summary>
        public static string SubTitleGameHistory {
            get {
                return ResourceManager.GetString("SubTitleGameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Info.
        /// </summary>
        public static string SubTitleMarketingInfo {
            get {
                return ResourceManager.GetString("SubTitleMarketingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SubTitlePreferences {
            get {
                return ResourceManager.GetString("SubTitlePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string SubTitleProfile {
            get {
                return ResourceManager.GetString("SubTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo History.
        /// </summary>
        public static string SubTitlePromoHistory {
            get {
                return ResourceManager.GetString("SubTitlePromoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending Trends (Last 3 Months).
        /// </summary>
        public static string SubTitleSpendingTrends {
            get {
                return ResourceManager.GetString("SubTitleSpendingTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Frequency Trend (Last 3 Months).
        /// </summary>
        public static string SubTitleVisitTrends {
            get {
                return ResourceManager.GetString("SubTitleVisitTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TabPreferencesAll {
            get {
                return ResourceManager.GetString("TabPreferencesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string TabPreferencesMonth {
            get {
                return ResourceManager.GetString("TabPreferencesMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Months.
        /// </summary>
        public static string TabPreferencesQuarter {
            get {
                return ResourceManager.GetString("TabPreferencesQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TabPreferencesToday {
            get {
                return ResourceManager.GetString("TabPreferencesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Search.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
