//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Configuration.UIConfiguration", typeof(UIConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Layout.
        /// </summary>
        public static string ChooseLayout {
            get {
                return ResourceManager.GetString("ChooseLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxed Layout with Top Menu.
        /// </summary>
        public static string ChooseLayoutBox {
            get {
                return ResourceManager.GetString("ChooseLayoutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Layout with Mini Left Menu.
        /// </summary>
        public static string ChooseLayoutFixed {
            get {
                return ResourceManager.GetString("ChooseLayoutFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Layout with Open Left Menu.
        /// </summary>
        public static string ChooseLayoutFixedOpen {
            get {
                return ResourceManager.GetString("ChooseLayoutFixedOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Layout Skins.
        /// </summary>
        public static string ChooseLayoutSkin {
            get {
                return ResourceManager.GetString("ChooseLayoutSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Refresh Rate.
        /// </summary>
        public static string ChooseRefreshRate {
            get {
                return ResourceManager.GetString("ChooseRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh by 15 Minutes.
        /// </summary>
        public static string RefreshBy15Mins {
            get {
                return ResourceManager.GetString("RefreshBy15Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh by 30 Minutes.
        /// </summary>
        public static string RefreshBy30Mins {
            get {
                return ResourceManager.GetString("RefreshBy30Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh by 5 Minutes.
        /// </summary>
        public static string RefreshBy5Mins {
            get {
                return ResourceManager.GetString("RefreshBy5Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string SkinBlack {
            get {
                return ResourceManager.GetString("SkinBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Light.
        /// </summary>
        public static string SkinBlackLight {
            get {
                return ResourceManager.GetString("SkinBlackLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string SkinBlue {
            get {
                return ResourceManager.GetString("SkinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Light.
        /// </summary>
        public static string SkinBlueLight {
            get {
                return ResourceManager.GetString("SkinBlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string SkinGreen {
            get {
                return ResourceManager.GetString("SkinGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Light.
        /// </summary>
        public static string SkinGreenLight {
            get {
                return ResourceManager.GetString("SkinGreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string SkinPurple {
            get {
                return ResourceManager.GetString("SkinPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Light.
        /// </summary>
        public static string SkinPurpleLight {
            get {
                return ResourceManager.GetString("SkinPurpleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string SkinRed {
            get {
                return ResourceManager.GetString("SkinRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Light.
        /// </summary>
        public static string SkinRedLight {
            get {
                return ResourceManager.GetString("SkinRedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string SkinYellow {
            get {
                return ResourceManager.GetString("SkinYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Light.
        /// </summary>
        public static string SkinYellowLight {
            get {
                return ResourceManager.GetString("SkinYellowLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Configuration Sidebar.
        /// </summary>
        public static string ToggleConfigSidebar {
            get {
                return ResourceManager.GetString("ToggleConfigSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Configuration Sidebar Skin.
        /// </summary>
        public static string ToggleConfigSidebarSkin {
            get {
                return ResourceManager.GetString("ToggleConfigSidebarSkin", resourceCulture);
            }
        }
    }
}
