//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Account.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the account.
        /// </summary>
        public static string AccountDeleteFailed {
            get {
                return ResourceManager.GetString("AccountDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation registration failed, please click the send email button to contact the support service. .
        /// </summary>
        public static string ConfirmationFailed {
            get {
                return ResourceManager.GetString("ConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token {0} was not able to be validated for user {1}..
        /// </summary>
        public static string ConfirmationFailureEmail {
            get {
                return ResourceManager.GetString("ConfirmationFailureEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation token failure..
        /// </summary>
        public static string ConfirmationFailureEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmationFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation New Password..
        /// </summary>
        public static string ConfirmationNewPassword {
            get {
                return ResourceManager.GetString("ConfirmationNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was succesfully confirmed, please click the LOGIN button to log into the system..
        /// </summary>
        public static string ConfirmationSuccess {
            get {
                return ResourceManager.GetString("ConfirmationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string CurrentPasswordInvalid {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured the email cannot be send..
        /// </summary>
        public static string EmailSentFailure {
            get {
                return ResourceManager.GetString("EmailSentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email was sent successfully..
        /// </summary>
        public static string EmailSentSuccess {
            get {
                return ResourceManager.GetString("EmailSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered empty user id..
        /// </summary>
        public static string EmptyUserId {
            get {
                return ResourceManager.GetString("EmptyUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and the confirmation password do not match..
        /// </summary>
        public static string NewPasswordMustMatch {
            get {
                return ResourceManager.GetString("NewPasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new user id already exist, you can not use it to register.
        /// </summary>
        public static string NewUserIdExist {
            get {
                return ResourceManager.GetString("NewUserIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the confirmation password do not match..
        /// </summary>
        public static string PasswordMustMatch {
            get {
                return ResourceManager.GetString("PasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset failed, please click the send email button to contact the support service..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for creating an account...
        ///&lt;br /&gt;
        ///&lt;p&gt;Before you can use your account we need to 
        ///verify your email address.&lt;/p&gt;
        ///&lt;p&gt;We just sent you an email with a confirmation 
        ///code. Please follow the instructions in the email 
        ///to validate your email address.&lt;/p&gt;.
        /// </summary>
        public static string RegisterEmailBody {
            get {
                return ResourceManager.GetString("RegisterEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember This Browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND EMAIL.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure both password values match..
        /// </summary>
        public static string TwoPasswordNotSame {
            get {
                return ResourceManager.GetString("TwoPasswordNotSame", resourceCulture);
            }
        }
    }
}
