//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_Users()
        {
            this.CFG_UserGroups = new HashSet<CFG_UserGroups>();
        }
    
        public string IDUser { get; set; }
        public string IDLanguage { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public bool MustChangePassword { get; set; }
        public short FailedLoginAttemps { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    
        public virtual CFG_Languages CFG_Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_UserGroups> CFG_UserGroups { get; set; }
    }
}
