//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_Casinos
    {
        public byte IDCasino { get; set; }
        public string Description { get; set; }
        public string LogoPath { get; set; }
        public string Address { get; set; }
        public int IDCountryCity { get; set; }
        public byte IDCasinoGroup { get; set; }
        public string IDLanguageByDefault { get; set; }
        public long IDPostalCode { get; set; }
        public string IDCultureInfo { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyName { get; set; }
        public string StandardCurrencyFormat { get; set; }
        public string CustomCurrencyFormat { get; set; }
        public string DecimalSymbol { get; set; }
        public string DigitGroupingSymbol { get; set; }
        public string StandardNumberFormat { get; set; }
        public string CustomNumberFormat { get; set; }
        public string ShortDateFormat { get; set; }
        public string ShortTimeFormat { get; set; }
        public string ShortDateTimeFormat { get; set; }
        public string LongDateFormat { get; set; }
        public string LongTimeFormat { get; set; }
        public string LongDateTimeFormat { get; set; }
    }
}
