//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_AppMenues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_AppMenues()
        {
            this.CFG_AppMenuesTranslation = new HashSet<CFG_AppMenuesTranslation>();
            this.CFG_AppMenuItems = new HashSet<CFG_AppMenuItems>();
            this.CFG_UserGroups = new HashSet<CFG_UserGroups>();
        }
    
        public int IDMenuHeader { get; set; }
        public byte IDApp { get; set; }
        public short Order { get; set; }
        public bool Enabled { get; set; }
    
        public virtual CFG_Apps CFG_Apps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenuesTranslation> CFG_AppMenuesTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenuItems> CFG_AppMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_UserGroups> CFG_UserGroups { get; set; }
    }
}
