//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_AppMenuItemsTranslation
    {
        public int IDMenuItem { get; set; }
        public string IDLanguage { get; set; }
        public string Description { get; set; }
        public string Tooltip { get; set; }
        public string Notes { get; set; }
    
        public virtual CFG_Languages CFG_Languages { get; set; }
        public virtual CFG_AppMenuItems CFG_AppMenuItems { get; set; }
    }
}
