//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_Languages()
        {
            this.CFG_AppMenuesTranslation = new HashSet<CFG_AppMenuesTranslation>();
            this.CFG_AppMenuItemsTranslation = new HashSet<CFG_AppMenuItemsTranslation>();
            this.CFG_Users = new HashSet<CFG_Users>();
        }
    
        public string IDLanguage { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenuesTranslation> CFG_AppMenuesTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenuItemsTranslation> CFG_AppMenuItemsTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_Users> CFG_Users { get; set; }
    }
}
