//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_AppMenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_AppMenuItems()
        {
            this.CFG_AppMenuItemsTranslation = new HashSet<CFG_AppMenuItemsTranslation>();
            this.CFG_UserGroups = new HashSet<CFG_UserGroups>();
        }
    
        public int IDMenuItem { get; set; }
        public int IDMenuHeader { get; set; }
        public string AssemblyPath { get; set; }
        public string AssemblyType { get; set; }
        public bool IsAssemblyPathAbsolute { get; set; }
        public short Order { get; set; }
        public bool Enabled { get; set; }
    
        public virtual CFG_AppMenues CFG_AppMenues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenuItemsTranslation> CFG_AppMenuItemsTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_UserGroups> CFG_UserGroups { get; set; }
    }
}
