//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_Apps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFG_Apps()
        {
            this.CFG_AppMenues = new HashSet<CFG_AppMenues>();
        }
    
        public byte IDApp { get; set; }
        public string Description { get; set; }
        public string AssemblyPath { get; set; }
        public string AssemblyType { get; set; }
        public bool CanEditAuthorizations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFG_AppMenues> CFG_AppMenues { get; set; }
    }
}
