//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBVersionGnSy
    {
        public int ID { get; set; }
        public int MajorVersion { get; set; }
        public int MinorVersion { get; set; }
        public int RevisionVersion { get; set; }
        public string TextVersion { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
