//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBI_CFG_DashboardCharts
    {
        public int ID { get; set; }
        public int DisplayOrder { get; set; }
        public string ChartName { get; set; }
        public string ChartGroupName { get; set; }
        public string ChartType { get; set; }
        public bool AddedToDashboard { get; set; }
        public string ChartIcon { get; set; }
        public string ChartBgColor { get; set; }
    }
}
