//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GenuinaDBEntities : DbContext
    {
        public GenuinaDBEntities()
            : base("name=GenuinaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GBI_CFG_DashboardCharts> GBI_CFG_DashboardCharts { get; set; }
        public virtual DbSet<CFG_AppMenuesTranslation> CFG_AppMenuesTranslation { get; set; }
        public virtual DbSet<CFG_AppMenuItemsTranslation> CFG_AppMenuItemsTranslation { get; set; }
        public virtual DbSet<CFG_Apps> CFG_Apps { get; set; }
        public virtual DbSet<CFG_Languages> CFG_Languages { get; set; }
        public virtual DbSet<CFG_Users> CFG_Users { get; set; }
        public virtual DbSet<CFG_AppMenues> CFG_AppMenues { get; set; }
        public virtual DbSet<CFG_AppMenuItems> CFG_AppMenuItems { get; set; }
        public virtual DbSet<CFG_UserGroups> CFG_UserGroups { get; set; }
        public virtual DbSet<CFG_Casinos> CFG_Casinos { get; set; }
        public virtual DbSet<DBVersionGnSy> DBVersionGnSys { get; set; }
    
        public virtual ObjectResult<SlotOccupationST> GetSlotOccupationList(string bD)
        {
            var bDParameter = bD != null ?
                new ObjectParameter("BD", bD) :
                new ObjectParameter("BD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SlotOccupationST>("GetSlotOccupationList", bDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetTotalSlots(Nullable<System.DateTime> dateTimeStart, Nullable<System.DateTime> dateTimeEnd)
        {
            var dateTimeStartParameter = dateTimeStart.HasValue ?
                new ObjectParameter("DateTimeStart", dateTimeStart) :
                new ObjectParameter("DateTimeStart", typeof(System.DateTime));
    
            var dateTimeEndParameter = dateTimeEnd.HasValue ?
                new ObjectParameter("DateTimeEnd", dateTimeEnd) :
                new ObjectParameter("DateTimeEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetTotalSlots", dateTimeStartParameter, dateTimeEndParameter);
        }
    
        public virtual ObjectResult<OperationSummaryST> GetOperationSummaryList(Nullable<System.DateTime> dateTimeStart, Nullable<System.DateTime> dateTimeEnd)
        {
            var dateTimeStartParameter = dateTimeStart.HasValue ?
                new ObjectParameter("DateTimeStart", dateTimeStart) :
                new ObjectParameter("DateTimeStart", typeof(System.DateTime));
    
            var dateTimeEndParameter = dateTimeEnd.HasValue ?
                new ObjectParameter("DateTimeEnd", dateTimeEnd) :
                new ObjectParameter("DateTimeEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperationSummaryST>("GetOperationSummaryList", dateTimeStartParameter, dateTimeEndParameter);
        }
    
        public virtual ObjectResult<OperationSummaryProviderST> GetOperationSummaryProviderList(Nullable<System.DateTime> dateTimeStart, Nullable<System.DateTime> dateTimeEnd)
        {
            var dateTimeStartParameter = dateTimeStart.HasValue ?
                new ObjectParameter("DateTimeStart", dateTimeStart) :
                new ObjectParameter("DateTimeStart", typeof(System.DateTime));
    
            var dateTimeEndParameter = dateTimeEnd.HasValue ?
                new ObjectParameter("DateTimeEnd", dateTimeEnd) :
                new ObjectParameter("DateTimeEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperationSummaryProviderST>("GetOperationSummaryProviderList", dateTimeStartParameter, dateTimeEndParameter);
        }
    
        public virtual ObjectResult<TopPlayerInfoST> GetTopPlayerList(Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd, Nullable<int> qty, Nullable<int> visit)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(int));
    
            var visitParameter = visit.HasValue ?
                new ObjectParameter("Visit", visit) :
                new ObjectParameter("Visit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopPlayerInfoST>("GetTopPlayerList", dateStartParameter, dateEndParameter, qtyParameter, visitParameter);
        }
    
        public virtual ObjectResult<OperationSummaryTrendST> GetOperationSummaryTrendList(Nullable<System.DateTime> day, string defaultStartTime, string defaultEndTime, Nullable<int> num)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(System.DateTime));
    
            var defaultStartTimeParameter = defaultStartTime != null ?
                new ObjectParameter("DefaultStartTime", defaultStartTime) :
                new ObjectParameter("DefaultStartTime", typeof(string));
    
            var defaultEndTimeParameter = defaultEndTime != null ?
                new ObjectParameter("DefaultEndTime", defaultEndTime) :
                new ObjectParameter("DefaultEndTime", typeof(string));
    
            var numParameter = num.HasValue ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperationSummaryTrendST>("GetOperationSummaryTrendList", dayParameter, defaultStartTimeParameter, defaultEndTimeParameter, numParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerST> GetMarketingPlayer(string iDPlayer)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerST>("GetMarketingPlayer", iDPlayerParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerReferencesST> GetMarketingPlayerReferences(string iDPlayer, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerReferencesST>("GetMarketingPlayerReferences", iDPlayerParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerTrendsST> GetMarketingPlayerTrends(string iDPlayer, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerTrendsST>("GetMarketingPlayerTrends", iDPlayerParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerActivityST> GetMarketingPlayerActivity(string iDPlayer, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerActivityST>("GetMarketingPlayerActivity", iDPlayerParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerCardsST> GetMarketingPlayerCards(string iDPlayer)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerCardsST>("GetMarketingPlayerCards", iDPlayerParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerCashDeskST> GetMarketingPlayerCashDesk(string iDPlayer)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerCashDeskST>("GetMarketingPlayerCashDesk", iDPlayerParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerGameHistoryST> GetMarketingPlayerGameHistory(string iDPlayer)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerGameHistoryST>("GetMarketingPlayerGameHistory", iDPlayerParameter);
        }
    
        public virtual ObjectResult<MarketingPlayerPromoST> GetMarketingPlayerPromo(string iDPlayer)
        {
            var iDPlayerParameter = iDPlayer != null ?
                new ObjectParameter("IDPlayer", iDPlayer) :
                new ObjectParameter("IDPlayer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingPlayerPromoST>("GetMarketingPlayerPromo", iDPlayerParameter);
        }
    }
}
