//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerActivityST
    {
        public decimal NetWin { get; set; }
        public decimal Handle { get; set; }
        public decimal BuyIn { get; set; }
        public int SessionTime { get; set; }
        public decimal PromoGranted { get; set; }
        public decimal PromoConsumed { get; set; }
    }
}
