//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerCashDeskST
    {
        public string BLCardNumber { get; set; }
        public System.DateTime Time { get; set; }
        public string TicketNumber { get; set; }
        public string Cashier { get; set; }
        public string Name { get; set; }
        public decimal AmountIN { get; set; }
        public decimal AmountOUT { get; set; }
    }
}
