//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerCardsST
    {
        public string BLCardNumber { get; set; }
        public string Status { get; set; }
        public string IssueMathod { get; set; }
        public Nullable<System.DateTime> FirstUse { get; set; }
        public decimal Balance { get; set; }
        public Nullable<long> IDPlayerAccount { get; set; }
    }
}
