//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerPromoST
    {
        public string Promo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateTimeAssigned { get; set; }
        public string BLCardNumberPaid { get; set; }
    }
}
