//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerGameHistoryST
    {
        public System.DateTime DateTimeStart { get; set; }
        public string Game { get; set; }
        public string Provider { get; set; }
        public string GameType { get; set; }
        public decimal WinLoss { get; set; }
        public int Duration { get; set; }
        public decimal Handle { get; set; }
        public int AverageBet { get; set; }
        public string SlotNUmber { get; set; }
    }
}
