//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerReferencesST
    {
        public string Game { get; set; }
        public string Provider { get; set; }
        public string GameType { get; set; }
        public Nullable<decimal> WinLoss { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Handle { get; set; }
        public int AverageBet { get; set; }
        public Nullable<int> Visits { get; set; }
    }
}
