//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerST
    {
        public string IDPlayer { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public string SlotNumber { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<decimal> Handle { get; set; }
        public Nullable<decimal> Win { get; set; }
        public string Active { get; set; }
        public string Category { get; set; }
        public int NRCredits { get; set; }
        public Nullable<decimal> LPAvailable { get; set; }
        public Nullable<decimal> LPConsumed { get; set; }
        public string Segment_RFM { get; set; }
        public string Segment_Classic { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Cellular { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Occupation { get; set; }
        public string Language { get; set; }
        public string MeritalStatus { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public Nullable<System.DateTime> AccountCreationDate { get; set; }
        public string DocType { get; set; }
        public string DocNumber { get; set; }
        public string NickName { get; set; }
    }
}
