//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class MarketingPlayerTrendsST
    {
        public Nullable<System.DateTime> LastWeekDay { get; set; }
        public Nullable<decimal> Handle { get; set; }
        public Nullable<int> Visits { get; set; }
    }
}
