//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class OperationSummaryProviderST
    {
        public string Description { get; set; }
        public byte IDGMManufacturer { get; set; }
        public Nullable<decimal> CashOut { get; set; }
        public Nullable<decimal> CashIN { get; set; }
        public Nullable<long> Sesiones { get; set; }
        public Nullable<long> CantPlayer { get; set; }
        public Nullable<decimal> HandPayments { get; set; }
        public Nullable<decimal> PROMO_IN { get; set; }
        public Nullable<decimal> PROMO_OUT { get; set; }
    }
}
