//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class OperationSummaryST
    {
        public Nullable<decimal> AmountIn { get; set; }
        public Nullable<decimal> AmountOut { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> TotalSesiones { get; set; }
        public Nullable<decimal> OcupacionActual { get; set; }
        public Nullable<decimal> OcupacionPeriodo { get; set; }
        public Nullable<decimal> Promociones { get; set; }
        public Nullable<decimal> EspecialPromo { get; set; }
        public Nullable<decimal> CanceledPromo { get; set; }
        public string NamePromo20 { get; set; }
        public Nullable<decimal> TotalHP { get; set; }
        public Nullable<decimal> TotalJP { get; set; }
        public Nullable<long> TotalSlots { get; set; }
        public Nullable<long> TotalSlotsOcuped { get; set; }
        public Nullable<decimal> AmountPlayerAccountVariation { get; set; }
        public Nullable<decimal> PlayerAccountIN { get; set; }
        public Nullable<decimal> PlayerAccountOUT { get; set; }
    }
}
