//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class OperationSummaryTrendST
    {
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<int> DayDifference { get; set; }
        public Nullable<decimal> HardSoftCountBill { get; set; }
        public Nullable<decimal> AmountIn { get; set; }
        public Nullable<decimal> AmountOut { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> HandPayments { get; set; }
        public Nullable<decimal> Jackpots { get; set; }
        public Nullable<decimal> CashIn { get; set; }
        public Nullable<decimal> CashOut { get; set; }
    }
}
