//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class SlotOccupationST
    {
        public Nullable<int> Hora { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> Players { get; set; }
        public Nullable<int> Slots { get; set; }
        public Nullable<int> TotalSession { get; set; }
        public Nullable<decimal> WinLoss { get; set; }
        public Nullable<decimal> Handle { get; set; }
        public Nullable<long> TotalPlayers { get; set; }
        public Nullable<long> TotalSlotsOcuped { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
    }
}
