//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Models
{
    using System;
    
    public partial class TopPlayerInfoST
    {
        public string PlayerName { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public string Gender { get; set; }
        public string LastVisit { get; set; }
        public Nullable<int> TotalVisits { get; set; }
        public Nullable<decimal> WinLoss { get; set; }
        public Nullable<decimal> Handle { get; set; }
        public string Telofono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
    }
}
