//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationSummary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Dashboard.OperationSummary", typeof(OperationSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh is Deactivated because the end time is less than the current time!.
        /// </summary>
        public static string BtnRefreshDisabledTooltip {
            get {
                return ResourceManager.GetString("BtnRefreshDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this to update report automatically!.
        /// </summary>
        public static string BtnRefreshTooltip {
            get {
                return ResourceManager.GetString("BtnRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reservation.
        /// </summary>
        public static string NetWin_TaxReservation {
            get {
                return ResourceManager.GetString("NetWin_TaxReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Tax from Win Player.
        /// </summary>
        public static string NetWin_TaxReservationTooltip {
            get {
                return ResourceManager.GetString("NetWin_TaxReservationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Win After Tax.
        /// </summary>
        public static string NetWinAfterTax {
            get {
                return ResourceManager.GetString("NetWinAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Money In - Total Money Out - Tax Reservation.
        /// </summary>
        public static string NetWinAfterTaxTooltip {
            get {
                return ResourceManager.GetString("NetWinAfterTaxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Money In.
        /// </summary>
        public static string NetWinCashIn {
            get {
                return ResourceManager.GetString("NetWinCashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Money Out.
        /// </summary>
        public static string NetWinCashOut {
            get {
                return ResourceManager.GetString("NetWinCashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Account Balance Fluctuation.
        /// </summary>
        public static string PlayerAccountBalance {
            get {
                return ResourceManager.GetString("PlayerAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash In.
        /// </summary>
        public static string PlayerCashIn {
            get {
                return ResourceManager.GetString("PlayerCashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Deposit + Coin Out Slots + HP + JP.
        /// </summary>
        public static string PlayerCashInTooltip {
            get {
                return ResourceManager.GetString("PlayerCashInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash Out.
        /// </summary>
        public static string PlayerCashOut {
            get {
                return ResourceManager.GetString("PlayerCashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin In Slots + Cash Out + Taxes.
        /// </summary>
        public static string PlayerCashOutTooltip {
            get {
                return ResourceManager.GetString("PlayerCashOutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string PromotionCancelled {
            get {
                return ResourceManager.GetString("PromotionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled &amp; Expired.
        /// </summary>
        public static string PromotionCancelledExpired {
            get {
                return ResourceManager.GetString("PromotionCancelledExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed.
        /// </summary>
        public static string PromotionConsumed {
            get {
                return ResourceManager.GetString("PromotionConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed Promotion on Slots.
        /// </summary>
        public static string PromotionConsumedOnSlot {
            get {
                return ResourceManager.GetString("PromotionConsumedOnSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not redeemable credits.
        /// </summary>
        public static string PromotionGranted {
            get {
                return ResourceManager.GetString("PromotionGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not redeemable credits.
        /// </summary>
        public static string PromotionGrantedTooltip {
            get {
                return ResourceManager.GetString("PromotionGrantedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over and Short.
        /// </summary>
        public static string PromotionOverAndShort {
            get {
                return ResourceManager.GetString("PromotionOverAndShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted Promotion - Canceladas &amp; Expiradas - Consumed Promotion on Slots.
        /// </summary>
        public static string PromotionOverShortTooltip {
            get {
                return ResourceManager.GetString("PromotionOverShortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Promotion.
        /// </summary>
        public static string PromotionSpecial {
            get {
                return ResourceManager.GetString("PromotionSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Facilities.
        /// </summary>
        public static string PromotionSpecialTooltip {
            get {
                return ResourceManager.GetString("PromotionSpecialTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Stats.
        /// </summary>
        public static string ProviderStatsTitle {
            get {
                return ResourceManager.GetString("ProviderStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Promo.
        /// </summary>
        public static string ProviderTableDPromotion {
            get {
                return ResourceManager.GetString("ProviderTableDPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Payments.
        /// </summary>
        public static string ProviderTableHandPayments {
            get {
                return ResourceManager.GetString("ProviderTableHandPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money In.
        /// </summary>
        public static string ProviderTableMoneyIn {
            get {
                return ResourceManager.GetString("ProviderTableMoneyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Out.
        /// </summary>
        public static string ProviderTableMoneyOut {
            get {
                return ResourceManager.GetString("ProviderTableMoneyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Win.
        /// </summary>
        public static string ProviderTableNetWin {
            get {
                return ResourceManager.GetString("ProviderTableNetWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string ProviderTablePlayers {
            get {
                return ResourceManager.GetString("ProviderTablePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string ProviderTableWin {
            get {
                return ResourceManager.GetString("ProviderTableWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string SlotEmpty {
            get {
                return ResourceManager.GetString("SlotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Occupation.
        /// </summary>
        public static string SlotOccupation {
            get {
                return ResourceManager.GetString("SlotOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Occupation Rate.
        /// </summary>
        public static string SlotOccupationRate {
            get {
                return ResourceManager.GetString("SlotOccupationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slots Occupied / Total Slots.
        /// </summary>
        public static string SlotOccupationRateTooltip {
            get {
                return ResourceManager.GetString("SlotOccupationRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string SlotOccupationSessions {
            get {
                return ResourceManager.GetString("SlotOccupationSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slots Occupied.
        /// </summary>
        public static string SlotOccupationTotalOccupied {
            get {
                return ResourceManager.GetString("SlotOccupationTotalOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Players.
        /// </summary>
        public static string SlotOccupationTotalPlayers {
            get {
                return ResourceManager.GetString("SlotOccupationTotalPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slots.
        /// </summary>
        public static string SlotOccupationTotalSlots {
            get {
                return ResourceManager.GetString("SlotOccupationTotalSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        public static string SlotOccupied {
            get {
                return ResourceManager.GetString("SlotOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Summary.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends in the Last 7 Days.
        /// </summary>
        public static string TrendsIn7Days {
            get {
                return ResourceManager.GetString("TrendsIn7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends in the Last 7 Weeks.
        /// </summary>
        public static string TrendsIn7Weeks {
            get {
                return ResourceManager.GetString("TrendsIn7Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Payments.
        /// </summary>
        public static string WinSlot_HandPayment {
            get {
                return ResourceManager.GetString("WinSlot_HandPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Pay + JackPot.
        /// </summary>
        public static string WinSlot_HandPaymentsTooltip {
            get {
                return ResourceManager.GetString("WinSlot_HandPaymentsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money In.
        /// </summary>
        public static string WinSlot_TotalMoneyIn {
            get {
                return ResourceManager.GetString("WinSlot_TotalMoneyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Out.
        /// </summary>
        public static string WinSlot_TotalMoneyOut {
            get {
                return ResourceManager.GetString("WinSlot_TotalMoneyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Promotion Consumed on Slots.
        /// </summary>
        public static string WinSlot_TotalPromotion {
            get {
                return ResourceManager.GetString("WinSlot_TotalPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIn Slots.
        /// </summary>
        public static string WinSlots {
            get {
                return ResourceManager.GetString("WinSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinIn - CoinOut - HP.
        /// </summary>
        public static string WinSlotTooltip {
            get {
                return ResourceManager.GetString("WinSlotTooltip", resourceCulture);
            }
        }
    }
}
