//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SlotOccupation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlotOccupation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Dashboard.SlotOccupation", typeof(SlotOccupation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Occupation Rate.
        /// </summary>
        public static string NumberSlotsOccupationRate {
            get {
                return ResourceManager.GetString("NumberSlotsOccupationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Handle.
        /// </summary>
        public static string NumberTotalHandle {
            get {
                return ResourceManager.GetString("NumberTotalHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slot Occupied.
        /// </summary>
        public static string NumberTotalSlotOccupied {
            get {
                return ResourceManager.GetString("NumberTotalSlotOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Slots.
        /// </summary>
        public static string NumberTotalSlots {
            get {
                return ResourceManager.GetString("NumberTotalSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors.
        /// </summary>
        public static string NumberTotalVisitors {
            get {
                return ResourceManager.GetString("NumberTotalVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Win.
        /// </summary>
        public static string NumberTotalWin {
            get {
                return ResourceManager.GetString("NumberTotalWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string OccupationTableHandle {
            get {
                return ResourceManager.GetString("OccupationTableHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string OccupationTablePlayers {
            get {
                return ResourceManager.GetString("OccupationTablePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate (%).
        /// </summary>
        public static string OccupationTableRate {
            get {
                return ResourceManager.GetString("OccupationTableRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string OccupationTableSessions {
            get {
                return ResourceManager.GetString("OccupationTableSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string OccupationTableSlots {
            get {
                return ResourceManager.GetString("OccupationTableSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string OccupationTableStartTime {
            get {
                return ResourceManager.GetString("OccupationTableStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string OccupationTableTime {
            get {
                return ResourceManager.GetString("OccupationTableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string OccupationTableWin {
            get {
                return ResourceManager.GetString("OccupationTableWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Occupation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Totals Slots.
        /// </summary>
        public static string TitleGrandTotalsSlots {
            get {
                return ResourceManager.GetString("TitleGrandTotalsSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles per Hour.
        /// </summary>
        public static string TitleHandlesPerHour {
            get {
                return ResourceManager.GetString("TitleHandlesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates [%] per Hour.
        /// </summary>
        public static string TitleRatesPerHour {
            get {
                return ResourceManager.GetString("TitleRatesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions per Hour.
        /// </summary>
        public static string TitleSessionsPerHour {
            get {
                return ResourceManager.GetString("TitleSessionsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots per Hour.
        /// </summary>
        public static string TitleSlotsPerHour {
            get {
                return ResourceManager.GetString("TitleSlotsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors per Hour.
        /// </summary>
        public static string TitleVisitorsPerHour {
            get {
                return ResourceManager.GetString("TitleVisitorsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss per Hour.
        /// </summary>
        public static string TitleWinlossPerHour {
            get {
                return ResourceManager.GetString("TitleWinlossPerHour", resourceCulture);
            }
        }
    }
}
