//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenuinaBI.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TopPlayers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TopPlayers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenuinaBI.Resources.Dashboard.TopPlayers", typeof(TopPlayers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number of top player!.
        /// </summary>
        public static string ParamPlayerNeeded {
            get {
                return ResourceManager.GetString("ParamPlayerNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unluckiest players.
        /// </summary>
        public static string ParamPlayerNumber {
            get {
                return ResourceManager.GetString("ParamPlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Players is Out of Maximum Limitation {0}..
        /// </summary>
        public static string ParamPlayersOutOfMaximum {
            get {
                return ResourceManager.GetString("ParamPlayersOutOfMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid visit number for top player!.
        /// </summary>
        public static string ParamVisitNeeded {
            get {
                return ResourceManager.GetString("ParamVisitNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having a Greater Number of Visits Than.
        /// </summary>
        public static string ParamVisitNumber {
            get {
                return ResourceManager.GetString("ParamVisitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Visits is Out of Maximum Limitation {0}..
        /// </summary>
        public static string ParamVisitsOutOfMaximum {
            get {
                return ResourceManager.GetString("ParamVisitsOutOfMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string PlayerListBirthday {
            get {
                return ResourceManager.GetString("PlayerListBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlayerListEmail {
            get {
                return ResourceManager.GetString("PlayerListEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PlayerListGender {
            get {
                return ResourceManager.GetString("PlayerListGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string PlayerListHandle {
            get {
                return ResourceManager.GetString("PlayerListHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visit.
        /// </summary>
        public static string PlayerListLastVisit {
            get {
                return ResourceManager.GetString("PlayerListLastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular.
        /// </summary>
        public static string PlayerListMobile {
            get {
                return ResourceManager.GetString("PlayerListMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlayerListPlayerName {
            get {
                return ResourceManager.GetString("PlayerListPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string PlayerListTelephone {
            get {
                return ResourceManager.GetString("PlayerListTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player List.
        /// </summary>
        public static string PlayerListTitle {
            get {
                return ResourceManager.GetString("PlayerListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visits.
        /// </summary>
        public static string PlayerListTotalVIsit {
            get {
                return ResourceManager.GetString("PlayerListTotalVIsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss.
        /// </summary>
        public static string PlayerListWinLoss {
            get {
                return ResourceManager.GetString("PlayerListWinLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Players.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
